u_domain_name       = "test-s3-20221008.net" # ここは書き換えること
u_env               = "Dev"
u_s3_acl            = "private"
u_object_key_name_html   = "index.html"
u_object_source_html     = "./src/index.html" # ここは書き換えること
u_contect_type_html      = "text/html"
u_object_key_name_css   = "css/"
u_object_source_css     = "./src/css/" # ここは書き換えること
u_object_key_name_js   = "js/"
u_object_source_js     = "./src/js/" # ここは書き換えること
u_region_ap_northeast_1 = "ap-northeast-1"
u_region_us_east_1 = "us-east-1"
