variable "u_domain_name" {}
variable "u_env" {}
variable "u_s3_acl" {}
variable "u_object_key_name_html" {}
variable "u_object_source_html" {}
variable "u_contect_type_html" {}
variable "u_object_key_name_css" {}
variable "u_object_source_css" {}
variable "u_object_key_name_js" {}
variable "u_object_source_js" {}
variable "u_region_ap_northeast_1" {}
variable "u_region_us_east_1" {}